# Generated by Django 3.0.2 on 2020-02-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200129_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/document/%Y/%m/%d/'),
        ),
    ]
