# Generated by Django 3.0.2 on 2020-02-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200203_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/document'),
        ),
    ]
