# Generated by Django 3.0.2 on 2020-02-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20200204_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snippets.Author'),
            preserve_default=False,
        ),
    ]
